@baseUrl = http://localhost:1234
@authToken = {{authenticate.response.body.token}}

# @name create_user
POST {{baseUrl}}/usuarios
Content-Type: application/json

{
    "nome": "Lais Helena",
    "email": "laishelena@email.com",
    "senha": "123456789"
}

###

# @name authenticate
POST {{baseUrl}}/usuarios/login
Content-Type: application/json

{
    "email": "laishelena@email.com",
    "senha": "123456789"
}

###

# @name get_user_by_email
GET {{baseUrl}}/usuarios/me
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

# @name create_category
POST {{baseUrl}}/categorias
Content-Type: application/json

{
    "nome": "Lazer"
    
}