version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=senhaSegura123
      - POSTGRESQL_DATABASE=mydb
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
